### ISSUE TITLE
Ubuntu 20.04 repo

### ISSUE THREAD

**Issue by rat** [RapidSVN/RapidSVN#41] opened 2020-07-04 20:25 UTC
I dont find a easy way to install in my Ubuntu 20.04. How i can install a current version of rapidsvn in atual lts ubuntu?

**Comment by jneiva08** [comment] 2020-09-07 21:29
I'm using linux mint 20, can't find rapidsvn when try to install by apt-get

**Comment by joergen7** [comment] 2020-11-17 09:00
I, too, had problems to install RapidSVN on my Ubuntu 20.04 box. After realizing that a `rapidsvn` package was missing from the apt sources. Then, I downloaded the RapidSVN tarball version 0.12.1 and tried building it from source but failed to.

I could not get the `configure` script to run. Initially, it would not find my Subversion libraries, although it finds the headers. I could fix that by running

    ./configure --with-svn-lib=/usr/lib/x86_64-linux-gnu/

But then the configure script did not like my wxWidgets. I have `libwxbase3.0-dev` installed but the configure script fails with the following line:

    configure: error: wxWidgets >= 2.4.2 required, found version 3.0.4

which is strange because 3.0.4 is clearly above 2.4.2. Does someone have any insight into what the problem is?

**Comment by XelaRellum** [comment] 2020-12-25 14:51
> ```
> configure: error: wxWidgets >= 2.4.2 required, found version 3.0.4
> ```
> 
> which is strange because 3.0.4 is clearly above 2.4.2. Does someone know what the problem is?

This is strange. If you take a look at the file configure.ac there is a check in line 176, that should match. You you insert `echo $WX_VERSION` before line 171? This might give us clues what is happening.

**Comment by joergen7** [comment] 2021-01-25 16:12
Hello, when pulling from [master](https://github.com/RapidSVN/RapidSVN/commit/4cc4ab28df15686ac2cdf930a649e082121505f4) and with `libapr1-dev`, `libaprutil1-dev`, `libsvn-dev`, `python-is-python3`, and `libwxbase3.0-dev` the configure script ran to the end. Now I seem to get errors that seem to come from within libxw. I get many pages of error messages. Here, only the last bit:

```
[...]
In file included from /usr/include/wx-3.0/wx/dialog.h:15,
                 from include/rapidsvn_generated.h:33,
                 from include/about_dlg.hpp:27,
                 from src/about_dlg.cpp:29:
/usr/include/wx-3.0/wx/containr.h: In instantiation of ‘void wxNavigationEnabled<W>::AddChild(wxWindowBase*) [with W = wxWindow]’:
/usr/include/wx-3.0/wx/containr.h:218:42:   required from here
/usr/include/wx-3.0/wx/containr.h:220:34: error: incomplete type ‘wxNavigationEnabled<wxWindow>::BaseWindowClass’ {aka ‘wxWindow’} used in nested name specifier
  220 |         BaseWindowClass::AddChild(child);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/include/wx-3.0/wx/containr.h:226:43: error: incomplete type ‘wxNavigationEnabled<wxWindow>::BaseWindowClass’ {aka ‘wxWindow’} used in nested name specifier
  226 |             if ( !BaseWindowClass::HasFlag(wxTAB_TRAVERSAL) )
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/containr.h:227:51: error: incomplete type ‘wxNavigationEnabled<wxWindow>::BaseWindowClass’ {aka ‘wxWindow’} used in nested name specifier
  227 |                 BaseWindowClass::ToggleWindowStyle(wxTAB_TRAVERSAL);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/containr.h: In instantiation of ‘void wxNavigationEnabled<W>::RemoveChild(wxWindowBase*) [with W = wxWindow]’:
/usr/include/wx-3.0/wx/containr.h:231:42:   required from here
/usr/include/wx-3.0/wx/containr.h:237:37: error: incomplete type ‘wxNavigationEnabled<wxWindow>::BaseWindowClass’ {aka ‘wxWindow’} used in nested name specifier
  237 |         BaseWindowClass::RemoveChild(child);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/include/wx-3.0/wx/containr.h: In instantiation of ‘void wxNavigationEnabled<W>::SetFocus() [with W = wxWindow]’:
/usr/include/wx-3.0/wx/containr.h:244:42:   required from here
/usr/include/wx-3.0/wx/containr.h:247:38: error: incomplete type ‘wxNavigationEnabled<wxWindow>::BaseWindowClass’ {aka ‘wxWindow’} used in nested name specifier
  247 |             BaseWindowClass::SetFocus();
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/wx-3.0/wx/containr.h: In instantiation of ‘void wxNavigationEnabled<W>::AddChild(wxWindowBase*) [with W = wxTopLevelWindow]’:
/usr/include/wx-3.0/wx/containr.h:218:42:   required from here
/usr/include/wx-3.0/wx/containr.h:220:34: error: ‘AddChild’ is not a member of ‘wxNavigationEnabled<wxTopLevelWindow>::BaseWindowClass’ {aka ‘wxTopLevelWindow’}
  220 |         BaseWindowClass::AddChild(child);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/include/wx-3.0/wx/containr.h:226:43: error: ‘HasFlag’ is not a member of ‘wxNavigationEnabled<wxTopLevelWindow>::BaseWindowClass’ {aka ‘wxTopLevelWindow’}
  226 |             if ( !BaseWindowClass::HasFlag(wxTAB_TRAVERSAL) )
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/containr.h:227:51: error: ‘ToggleWindowStyle’ is not a member of ‘wxNavigationEnabled<wxTopLevelWindow>::BaseWindowClass’ {aka ‘wxTopLevelWindow’}
  227 |                 BaseWindowClass::ToggleWindowStyle(wxTAB_TRAVERSAL);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/containr.h: In instantiation of ‘void wxNavigationEnabled<W>::RemoveChild(wxWindowBase*) [with W = wxTopLevelWindow]’:
/usr/include/wx-3.0/wx/containr.h:231:42:   required from here
/usr/include/wx-3.0/wx/containr.h:237:37: error: ‘RemoveChild’ is not a member of ‘wxNavigationEnabled<wxTopLevelWindow>::BaseWindowClass’ {aka ‘wxTopLevelWindow’}
  237 |         BaseWindowClass::RemoveChild(child);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/include/wx-3.0/wx/containr.h: In instantiation of ‘void wxNavigationEnabled<W>::SetFocus() [with W = wxTopLevelWindow]’:
/usr/include/wx-3.0/wx/containr.h:244:42:   required from here
/usr/include/wx-3.0/wx/containr.h:247:38: error: ‘SetFocus’ is not a member of ‘wxNavigationEnabled<wxTopLevelWindow>::BaseWindowClass’ {aka ‘wxTopLevelWindow’}
  247 |             BaseWindowClass::SetFocus();
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~^~
make[2]: *** [Makefile:1035: librapidsvn_la-about_dlg.lo] Error 1
make[2]: Leaving directory '/home/jorgen/RapidSVN/librapidsvn'
make[1]: *** [Makefile:1670: all-recursive] Error 1
make[1]: Leaving directory '/home/jorgen/RapidSVN/librapidsvn'
make: *** [Makefile:399: all-recursive] Error 1
```

**Comment by XelaRellum** [comment] 2021-01-27 07:28
I just checked it on my computer running 20.04 with all the current updates installed. For wx I think I installed wxGTK 3.0. Lots of warnings (deprecation of subversion functions as well as stuff caused by changes in wx during the last decade...).

**Comment by marcocod** [comment] 2021-03-23 15:06
I installed this version of RapidSVN on ubuntu 20.04 with the following steps:
- install the packages libgtk2.0-dev, libsvn-dev and python
- download the sources and install the library wxWidgets-2.9.5 with:
./configure --prefix={RAPIDSVN_PREFIX}
- make sure the command python link to python3
- install the rapidSVN with:
./configure --prefix={RAPIDSVN_PREFIX} --with-wx-config={RAPIDSVN_PREFIX}/bin/wx-config

This executable works, the only problem is that an assertion fails:

./src/common/strvararg.cpp(658): assert "n <= parser.nargs" failed in DoGetArgumentType(): more arguments than format string specifiers?
/home/marco/Software/rapidsvn2/include/wx-2.9/wx/strvararg.h(511): assert "(argtype & (wxFormatString::Arg_String)) == argtype" failed in wxArgNormalizerWithBuffer(): format specifier doesn't match argument type

This message can be hidden and ignored, but if someone can fix it, it should be better.

**Comment by marcocod** [comment] 2021-03-24 13:17
I discovered how to solve the assertion problem.
Before to build the wxWidgets library, in the file:

include/wx/debug.h

at the line 46 the define wxDEBUG_LEVEL must be set as 0 (instead of 1)
I think the same can be done with compilation flags, but I wanted to be sure.
Now the assertion fail messages don't appear anymore.

**Comment by XelaRellum** [comment] 2021-08-02 06:30
Ok, I think we can close this issue. If somebody wants to remove some warnings, please create a PR.

**Closed by XelaRellum** 2021-08-02 06:30 UTC

**Comment by tititiou36** [comment] 2021-08-10 18:06
To answer the initial question, you can also download the .deb package from 
   https://pkgs.org/download/rapidsvn
and install the one that was provided for 18.04

In my case, I also needed to install 2 another packages via .deb files available in https://pkgs.org/download/ for 18.04).

Looks to work fine with Ubuntu 21.04.
